
version: '3.8'

services:
  book_catalog_php_container:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: book_catalog_php_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9003

  book_catalog_nginx_container:
    image: nginx:latest
    container_name: book_catalog_nginx_container
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/BookCatalogAPI/public/:/app/apps/BookCatalogAPI/public
    depends_on:
      - book_catalog_php_container
