doctrine:
    dbal:
        dbname: '%env(resolve:DATABASE_NAME)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_ROOT_PASSWD)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            BookCatalog:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/../../src/BookCatalog/Infrastructure/Persistence/Doctrine/'
                prefix: 'BookCatalog\Domain'
                alias: BookCatalog
